<?php
/******************CRM TABLE PREFIX BY SIDDHARTH**************************/
define('CRM_TABLE_PREFIX','LEAD');
define('CRM_TABLE_SEPARATOR','_');

define('ADMIN_CRM','PROPTIGER_ADMIN');

define("USER" , "USER_LOGIN");
define("LEAD" , "LEADS");
define("L_DETAILS" , CRM_TABLE_PREFIX . CRM_TABLE_SEPARATOR. "DETAILS");
define("L_HISTORY" , CRM_TABLE_PREFIX . CRM_TABLE_SEPARATOR. "HISTORY");
define("L_ASSIGN" , CRM_TABLE_PREFIX . CRM_TABLE_SEPARATOR. "ASSIGN");
define("L_STATUS" , CRM_TABLE_PREFIX . CRM_TABLE_SEPARATOR. "STATUS");

define("MASTER_STATUS" , "MASTER" .CRM_TABLE_SEPARATOR. "STATUS");
define("MASTER_SOURCE" , "MASTER" . CRM_TABLE_SEPARATOR. "SOURCE");
define("MASTER_DEAD_REASON" , "MASTER" . CRM_TABLE_SEPARATOR. "DEAD". CRM_TABLE_SEPARATOR. "REASON");
define("LEAD_DESCRIPTION_HISTORY",LEAD_DESCRIPTION_HISTORY);
/******************CRM TABLE PREFIX**************************/
?>