<?php
    /***********stages*******/
    define("NewProject_stage","NewProject");
    define("NoStage_stage","NoStage");
    define("SecondaryPriceCycle_stage","SecondaryPriceCycle");
    define("UpdationCycle_stage","UpdationCycle");
    /***********phases*******/
    define("Audit1_phase","Audit1");
    define("Audit2_phase","Audit2");
    define("Complete_phase","Complete");
    define("DataCollection_phase","DataCollection");
    define("DcCallCenter_phase","DcCallCenter");
    define("NewProject_phase","NewProject");
    define("NoStage_phase","NoStage");
    define("Revert_phase","Revert");
?>
